# Generated by Django 5.1.4 on 2025-02-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], default='manager', help_text='Designates the role this user belongs to', max_length=25, verbose_name='user role'),
        ),
    ]
