# Generated by Django 5.1.4 on 2025-02-27 19:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Unique name of the company', max_length=255, unique=True)),
                ('manager', models.ForeignKey(help_text='User responsible for managing this company', on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the department', max_length=255)),
                ('company', models.ForeignKey(help_text='Company this department belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='companies.company')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Full name of the employee', max_length=255)),
                ('status', models.CharField(choices=[('application received', 'Application Received'), ('interview scheduled', 'Interview Scheduled'), ('not accepted', 'Not Accepted'), ('hired', 'Hired')], default='application received', help_text='Current status in the hiring workflow', max_length=255)),
                ('email', models.EmailField(help_text='Unique email address', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('mobile', models.CharField(help_text='Mobile number in international format', max_length=255, validators=[django.core.validators.RegexValidator(message='Mobile number must be in international format: +1234567890', regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.CharField(help_text='Physical address', max_length=255)),
                ('designation', models.CharField(help_text='Job title/position', max_length=255)),
                ('hired_on', models.DateField(blank=True, help_text='Date when employee was hired (only set when status is HIRED)', null=True)),
                ('department', models.ForeignKey(help_text='Department this employee belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.department')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['-created_at'], name='companies_c_created_a89ef1_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['-created_at'], name='companies_d_created_456603_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['-created_at'], name='companies_e_created_4ecad1_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status'], name='companies_e_status_0ac082_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['hired_on'], name='companies_e_hired_o_f2bf04_idx'),
        ),
    ]
